export const SET_BRANDS = "SET_BRANDS";
export const SET_BRANDS_ERROR = "SET_BRANDS_ERROR";
export const SET_BRANDS_LOADING = "SET_BRANDS_LOADING";
export const SAVE_BRAND = "SAVE_BRAND";
export const CREATE_BRAND = "CREATE_BRAND";
export const DELETE_BRAND = "DELETE_BRAND";

export const SET_PRODUCTS = "SET_PRODUCTS";
export const SET_PRODUCTS_ERROR = "SET_PRODUCTS_ERROR";
export const SET_PRODUCTS_LOADING = "SET_PRODUCTS_LOADING";
export const SAVE_PRODUCT = "SAVE_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const SELECT_PRODUCT = "SELECT_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";

export const SET_CLIENTS = "SET_CLIENTS";
export const SET_CLIENTS_ERROR = "SET_CLIENTS_ERROR";
export const SET_CLIENTS_LOADING = "SET_CLIENTS_LOADING";

export const SET_SALES = "SET_SALES";
export const SET_SALES_ERROR = "SET_SALES_ERROR";
export const SET_SALES_LOADING = "SET_SALES_LOADING";

export const CART_ADD_PRODUCT = "CART_ADD_PRODUCT";
export const CART_DELETE_PRODUCT = "CART_DELETE_PRODUCT";
